[opener]
open = [
  { run = 'xdg-open "$1"', desc = "Open" },
]
extract = [
  { run = 'ouch d -y "$@"', desc = "Extract here with ouch" },
]
edit = [
  { run = '${EDITOR:-vi} "$@"', desc = "Edit", block = true, for = "unix" },
]
view = [
  { run = 'geeqie "$1"', desc = "View" },
]
play = [
  { run = 'mpv --force-window "$@"', orphan = true, desc = "Play" },
]

[open]
rules = [
  # Text"edit",
  { mime = "text/*", use = "edit" },
  # Image
  { mime = "image/*", use = "view" },
  # Media
  { mime = "{audio,video}/*", use = "play" },
  # Archive
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = "extract" },
  # Fallback
  { url = "*", use = "open" },
]
