# modify_font cell_height 120%
# Background
background_opacity 1
background_blur 1
background          #3b3228
foreground          #AFD2E9
selection_foreground #3b3228
selection_background #f8e2a0

# colors
        # black
color0              #3b3228
color8              #5d4f40
        # red
color1              #e86045
color9              #e86045
        # green
color2              #92a650
color10             #92a650
        # yellow
color3              #e68d53
color11             #e68d53
        # blue
color4              #c1a387
color12             #c1a387
        # magenta
color5              #f8e2a0
color13             #f8e2a0
        # cyan
color6              #3eccbe
color14             #3eccbe
        # white
color7              #afd2e9
color15             #afd2e9



color16   #3b3228
color17   #43392d
color18   #4c4134
color19   #5d4f40
color20   #6b6055
color21   #c1a387
color22   #e86045
color23   #92a650
color24   #ace1af
color25   #e68d53
color26   #f8e2a0
color27   #afd2e9
color28   #3eccbe
color29   #868686
color30   #15156b
color31   #2c2c44


# Cursor
cursor #AFD2E9
cursor_shape beam
cursor_shape_unfocused block

window_padding_width 0 
window_margin_width 0 0 0 0
window_border_width 0pt
single_window_margin_width 0
single_window_padding_width 0
active_border_color #ff00ff
# active_border_color none
tab_bar_background #00ff00
placement_strategy bottom-left

enable_audio_bell no
hide_window_decorations yes

#       fontstuff

#    keybinds
map ctrl+shift+return
map ctrl+shift+t
# map ctrl+up scroll_line_up
# map ctrl+down scroll_line_down
# map ctrl+shift+up scroll_to_prompt -1
# map ctrl+shift+down scroll_to_prompt 1

# symbol_map U+2014 Noto Sans CJK JP
# narrow_symbols U+2014 2
# BEGIN_KITTY_FONTS
font_size 12
font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-ExtraLight features='zero cv01 cv06 cv07 cv10 cv11 cv12 cv16'
bold_font        family='JetBrainsMono Nerd Font Mono' style=Bold features='+zero cv01=0 cv06=0 cv07=0 cv10=0 cv11=0 cv12=0 cv16=0'
italic_font      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-ExtraLightItalic features='zero cv01 cv06 cv07 cv10 cv11 cv12 cv16'
bold_italic_font auto
# END_KITTY_FONTS
