# ~/.config/starship.toml

format = '''
[╭](bright white)${custom.glyphs}
[ ]()$hostname$directory$git_branch$git_status
[╰]()$status'''
add_newline = true

[status]
format = "$symbol"
symbol = "[󰝾](red) "
not_executable_symbol = "[󰝾](red) "
success_symbol = "[󰝾](bright white) "
not_found_symbol = "[󰝾](bright white) "
signal_symbol = "[󰝾](bright white) "
sigint_symbol = "[󰝾](bright white) "
map_symbol = true
disabled = false

[directory]
style = "blue"
read_only = ""
read_only_style = "red"
truncation_length = 3
truncation_symbol = ".../"
truncate_to_repo = true  # truncates directory to root folder if in github repo

[hostname]
ssh_only = true
format = "$hostname "
aliases = { "hachiko" = "\u001B[38;2;62;204;190m󰩄", "IrregularNotes" = "\u001B[38;2;193;163;135m󰎌", "pablotronica" = "\u001B[38;2;193;163;135m󰩃", "twister" = "\u001B[38;2;62;204;190m𖦹" }

[git_branch]
symbol = "𖣂"
always_show_remote = true
format = "[$symbol $branch ]($style)"
style = "green"

[git_status]
format = "([$ahead_behind$staged$deleted$modified$untracked$stashed]($style))"
style = "green"
untracked = "[?](yellow)"
stashed = "[$count](cyan)"
modified = "[~$count](yellow)"
staged = "[+$count](green)"
deleted = "[-$count](red)"
up_to_date = "[󰺕](bright green)"
ahead = "[⇡$count](green)"
behind = "[⇣$count|](red)"
conflicted = "[!!](red)"
renamed = "[»$count](yellow)"

[custom.glyphs]
format = "[$output](bright white)"
command = "python3 ~/.config/starship/glyphs_long.py"
shell = ["bash", "--noprofile", "--norc"]
when = true

# 󰝾
# 𖢊𖦋𖢏𖢴𖤲𖤱𖦹𖧻
