vim.treesitter.start()
vim.cmd('syntax match Emdash "—" conceal cchar=𖢊')
vim.cmd('syntax region ScarletText matchgroup=Conceal start="+R|" end="|+" concealends')
vim.cmd('syntax region MossText matchgroup=Conceal start="+G|" end="|+" concealends')
vim.cmd('syntax region SandText matchgroup=Conceal start="+S|" end="|+" concealends')
vim.cmd('syntax region SaffronText matchgroup=Conceal start="+Y|" end="|+" concealends')
vim.cmd('syntax region OrangeText matchgroup=Conceal start="+O|" end="|+" concealends')
vim.cmd('syntax region CyanText matchgroup=Conceal start="+B|" end="|+" concealends')
vim.cmd('syntax region CeladonText matchgroup=Conceal start="+T|" end="|+" concealends')
